import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'antd/dist/reset.css'; // Recommended for Ant Design v5+
import Header from "./components/Header";
import ReduxProvider from "@/store/provider";
import Theme from "./components/Theme";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          {/* <Header/> */}
        </header>
        <main>
        <Theme>
        <ReduxProvider>
        {children}
        </ReduxProvider>
        </Theme>
        </main>
        <footer>
          
        </footer>
      </body>
    </html>
  );
}
